version: "3"
services:
  compute_node:
    image: myimage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    command: "python -u manager.py run_node --host 0.0.0.0 --port ${PORT} --uploads_dir /home/uploads"
