FROM python:3.8

RUN groupadd -r uwsgi && useradd -r -g uwsgi uwsgi
RUN pip install flask uWSGI

WORKDIR /distllm

COPY distllm /distllm
COPY cmd.sh /

EXPOSE 9090 9191 5000
USER uwsgi

ENV LD_LIBRARY_PATH /distllm
CMD ["/cmd.sh"]